# Generated by Django 4.2.7 on 2023-11-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_model',
            name='user',
        ),
    ]
